-- 음식 종류별로 즐겨찾기 수가 가장 많은 식당
-- 음식 종류, ID, 식당이름, 즐격찾기 수 조회
-- 음식 가격 기준 내림차순
SELECT RI1.FOOD_TYPE, RI1.REST_ID, RI1.REST_NAME, RI2.FAVORITES
FROM REST_INFO RI1
INNER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
      FROM REST_INFO
      GROUP BY FOOD_TYPE) AS RI2
ON RI1.FOOD_TYPE = RI2.FOOD_TYPE AND RI1.FAVORITES = RI2.FAVORITES
ORDER BY RI1.FOOD_TYPE DESC;

