-- 이름, 보호 시작일 조회
-- 아직 입양을 못간 동물 중, 가장 오래 보호소에 있었던 동물 3마리
-- 보호 시작일 순으로
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME ASC
LIMIT 3;